apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltakspenger-meldekort-microfrontend
  namespace: tpts
  labels:
    team: tpts
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: tiltakspenger-meldekort-api
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
  env:
    - name: MELDEKORT_API_URL
      value: http://tiltakspenger-meldekort-api
    - name: MELDEKORT_API_SCOPE
      value: dev-gcp:tpts:tiltakspenger-meldekort-api
    - name: MELDEKORT_URL
      value: https://www.nav.no/tiltakspenger/meldekort
